# Generated by Django 4.2.4 on 2023-08-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Andrada_3preentrega_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
