# Generated by Django 4.2.4 on 2023-08-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Andrada_3preentrega_APP', '0002_alter_empleados_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='numero_sector',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre_sector',
            field=models.CharField(max_length=50),
        ),
    ]
